### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by armstrongsouljah**
This PR seeks to add the `ui` code. 
Any reviews are welcome
[github pages](https://armstrongsouljah.github.io/Store-Manager/ui/)
login details are in the `README.md`
@codjoero @BarnaTB @EmmellaBeatrice @Masete @bekeplar @habatkasa

### CODE REVIEW

**Comment by codjoero** [comment]
Hi man...looking good. Viewed on phone and after login in the page gets  mixed up... 
Am also trying to work on that on my end

**Comment by armstrongsouljah** [comment]
Will try to fix the responsiveness, thank you for pointing that out.

**Comment by habatkasa** [comment]
nice work ...  
in the user account
my concern though is with:
-the colors. would you consider changing text to white, then the hover bgcolor to black, may be that could create some balance.
-the position of the search box and the add product bar, i suggest you put one below the list.

**Comment by armstrongsouljah** [comment]
Thanks @habatkasa will work on those tomorrow.

**Comment by BeatriceNakabanda** [comment]
nice work

**Review by BarnaTB — CHANGES_REQUESTED** [review]
Your side navigation bar would be nicer if the whole box for a specific link could be a link instead of having to click the word itself.
Great Work though!

**Comment by bekeplar** [comment]
Work on the responsiveness bro

**Comment by bekeplar** [comment]
Ensure that your app works well on phone

**Comment by armstrongsouljah** [comment]
will do that after, Church. thank you.

**Comment by Qadriyah** [comment]
Make a sale has 3 menu items while other pages have 4. Put some padding on the input fields. I would propose you use the same colors on both admin and attendant sides. Otherwise good work

**Comment by bekeplar** [comment]
consider a user using a phone...things mix up after longing in

**Comment by armstrongsouljah** [comment]
Working on the responsiveness. Thank you all for the pointers.

**Comment by armstrongsouljah** [comment]
Yes it has 3 links on purpose. Am indicating that its the currently
accessed page thus no need to put a link that goes to itself.

**Comment by armstrongsouljah** [comment]
Hey team, I have fixed the css bugs and updated the [gh-pages](mstrongsouljah.github.io/Store-Manager/ui/)

**Pull request merged**
