### PR TITLE
161090714 admin views sales

### PR DESCRIPTION
**Pull request by armstrongsouljah**
Hey guys, this PR seeks to add the ability for the admin to view sales made by different sales attendants
@tomuhenry @habatkasa @codjoero @sanya-keneth
You may view it live [here](https://armstrongsouljah.github.io/Store-Manager/ui/index.html)
`Note:` Login using `admin` and `password` to be sent to the admin dashboard.
Thanks for taking time off to review my work.

### CODE REVIEW

**Comment by codjoero** [comment]
Tried to login but git a plain text "welcome user"

**Comment by armstrongsouljah** [comment]
> Tried to login but git a plain text "welcome user"

You were sent to the attendant dashboard which i haven't started on
retry using
*username:* `admin`
*password:* `password`

**Comment by codjoero** [comment]
Looks good man,
You could add some @media rules to throw the side bar under the main content on small screens

**Comment by armstrongsouljah** [comment]
@codjoero Will work on that right away.

**Comment by habatkasa** [comment]
nice work @armstrongsouljah 
would you consider adding something like a border on the login form? its kind of hard to identify it from the background.
then also on the admin view sales page, make the table headers user friendly. for example, "attendant_id"maybe hard to understand compared to "attendant id"

**Pull request merged**
